CREATE TABLE IF NOT EXISTS
  "units" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR NOT NULL,
    "created" timestamp(0) with time zone NOT NULL DEFAULT NOW()
  );

INSERT INTO
  units (name)
VALUES
  ('ml (mililitry)'),
  ('l (litry)'),
  ('łyżeczka (łyżeczki)'),
  ('łyżka (łyżki)'),
  ('szklanka (szklanki)'),
  ('g (gramy)'),
  ('kg (kilogramy)'),
  ('szt. (sztuka/sztuki)'),
  ('plaster (plastry)'),
  ('ząbek (ząbki) [np. czosnku]'),
  ('listek (listki) [np. laurowy, bazylii]'),
  ('garść (garście)'),
  ('szczypta (szczypty)'),
  ('kropla (krople)');
