CREATE TABLE IF NOT EXISTS
  "users" (
    "id" INTEGER NOT NULL UNIQUE,
    "name" VARCHAR NOT NULL,
    "email" VARCHAR NOT NULL UNIQUE,
    "hashed_password" VARCHAR NOT NULL,
    "created" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    FOREIGN KEY ("id") REFERENCES "recipies" ("user_id") ON UPDATE NO ACTION ON DELETE SET DEFAULT
  );
