CREATE TABLE IF NOT EXISTS
  "users" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR NOT NULL,
    "email" VARCHAR NOT NULL UNIQUE,
    "hashed_password" VARCHAR NOT NULL,
    "created" timestamp(0) with time zone NOT NULL DEFAULT NOW()
  );
